# -*- coding: utf-8 -*-
"""Matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKrPxUskgfvuq0WpaoWlJCoHuIYwGC5c

### **Title**: Introduction to Matrices in Python

#### **1. Introduction to Matrices**
A matrix is a collection of numbers arranged in rows and columns, often used to store data or perform calculations. In Python, we can represent a matrix as a list of lists, where each inner list represents a row.

Example:

```python
# A 2x3 matrix
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

# Accessing elements
print("Element at row 1, column 2:", matrix[0][1])
```

#### **Exercise 1: Creating a Simple Matrix**
Create a 3x2 matrix with any numbers you like. Then, print the matrix.
"""

# your code here
M = [[2, 4], [4, 6], [8, 2] ]

"""#### **2. Accessing Elements in a Matrix**
To access elements in a matrix, we use two indices: one for the row and one for the column. The first index (matrix[row][col]) is the row, and the second is the column.

Example:

```python
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

# Access the element in the second row and third column
element = matrix[1][2]
print("Element in second row, third column:", element)
```

#### **Exercise 2: Practice Accessing Elements**
Given the matrix below, print:
1. The first row.
2. The element in the third row, second column.

```python
matrix = [
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
]

"""

# your code here
print(matrix[0])
print(matriz[2][1])

"""#### **3. Modifying Elements in a Matrix**
You can also modify elements in a matrix by assigning a new value to a specific position.

Example:

```python
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

# Change the element in the first row, second column
matrix[0][1] = 20
print("Modified matrix:", matrix)
```

#### **Exercise 3: Modify Elements**
1. Change the second element in the second row to `99`.
2. Change the first element in the first row to `100`.

```python
matrix = [
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
]

"""

# your code here
matrix[1][1] = 99
matrix[0][0] = 100

"""#### **4. Adding Rows and Columns**
To add a new row, use `append`. To add a new column, you need to go through each row and add an element.

Example:

```python
# Adding a row
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

matrix.append([7, 8, 9])
print("Matrix with a new row:", matrix)

# Adding a column
for row in matrix:
    row.append(0)  # Adds a new column with 0 in each row

print("Matrix with a new column:", matrix)
```

#### **Exercise 4: Adding Rows and Columns**
1. Add a new row `[16, 17, 18]` to the matrix below.
2. Add a new column filled with `1`s.

```python
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

"""

# your code here
matrix = [
    [1, 2, 3], # [1, 2, 3 , nc]
    [4, 5, 6], # [4, 5, 6 , nc]
    [7, 8, 9]  # [7, 8, 9 , nc]
]
# matrix = [element1, element2, element3] -> , element4]
matrix.append([6,7,8])

for row in matrix:
  row.append(0)

for row in matrix:
  for col in row:
    print(col)

"""#### **5. Matrix Operations: Sum of Elements in a Row**
We can use loops to perform calculations on matrices. Here, we'll find the sum of all elements in a specific row.

Example:

```python
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

# Sum of elements in the first row
row_sum = 0
for element in matrix[0]:
    row_sum += element

print("Sum of the first row:", row_sum)
```

#### **Exercise 5: Row Sum**
Calculate the sum of elements in the second row of the matrix below.

```python
matrix = [
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
]

"""

# your code here
matrix = [
    [10, 11, 12], # 00, 01, 02
    [13, 14, 15], # 10, 11, 12
]
sr = matrix[1]
sum = 0
for element in sr:
  sum += element
print(sum)

ts = 0
for row in matrix:
  for col in row:
    print(col)
    ts += col
print(ts)

matrix = [
    [10, 11, 12], # 00, 01, 02
    [13, 14, 15], # 10, 11, 12
]

#print(len(matrix))
#print(len(matrix[0]))

for row in range(len(matrix)):
  for col in range(len(matrix[0])):
    # position row, col
    print(matrix[row][col])

"""#### **6. Matrix Transpose**
A transpose of a matrix flips its rows and columns. Here’s how to calculate it.

Example:

```python
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

transpose = []
for col in range(3):  # Assuming 3 columns
    new_row = []
    for row in range(2):  # Assuming 2 rows
        new_row.append(matrix[row][col])
    transpose.append(new_row)

print("Transpose:", transpose)
```

#### **Exercise 6: Matrix Transpose**
Write code to find the transpose of this matrix:

```python
matrix = [
    [7, 8, 9],
    [10, 11, 12]
]

"""

# your code here